# Generated by Django 5.2 on 2025-04-14 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='vacation_days',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
