# Generated by Django 5.2 on 2025-04-17 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_customuser_vacation_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='vacation_days_old',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
