# Generated by Django 5.2 on 2025-04-17 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_customuser_vacation_days_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='signature',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
